### ISSUE TITLE
Save user swipes to backend

### ISSUE THREAD

**Issue by mango23322** [HellowLab/DblFeature#24]
- [x] - On swipe update movieResults
- [x] - add screen to view all my swipes 
- [x] - add ability to edit movieResults (watched, ranking, etc)
- [x] - backend: add "check" to see if a user has already swiped on this movie, prior to creating a duplicate entry

**Comment by mango23322** [comment]
Editing the swipes works. Need to add the code to add/edit the star rating. Should only be a few lines of code for the api PUT

**Comment by mango23322** [comment]
Done!

**Comment by SeanKudrna** [comment]
Closing due to OP's completion report.
